"""add relationship for case_category

Revision ID: 33f1f9efe167
Revises: 8cb018191244
Create Date: 2025-04-14 23:02:43.937481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f1f9efe167'
down_revision: Union[str, None] = '8cb018191244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               existing_comment='наименование категории дела')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_comment='наименование категории дела')
    # ### end Alembic commands ###
