"""add judge last name

Revision ID: 5746cd5592a9
Revises: bc6c88fb6b8d
Create Date: 2025-04-12 20:28:31.546046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5746cd5592a9'
down_revision: Union[str, None] = 'bc6c88fb6b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge', sa.Column('last_name', sa.String(length=255), nullable=True, comment='фамилия судьи'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judge', 'last_name')
    # ### end Alembic commands ###
