"""'new_bd1'

Revision ID: 762f98969a20
Revises: c8dcafa504bc
Create Date: 2025-05-03 01:00:16.845516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762f98969a20'
down_revision: Union[str, None] = 'c8dcafa504bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'case', ['id'])
    op.create_unique_constraint(None, 'case_category', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'court', ['id'])
    op.create_unique_constraint(None, 'judge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judge', type_='unique')
    op.drop_constraint(None, 'court', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'case_category', type_='unique')
    op.drop_constraint(None, 'case', type_='unique')
    # ### end Alembic commands ###
