"""init migration

Revision ID: bc6c88fb6b8d
Revises: 
Create Date: 2025-04-12 20:17:50.044545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6c88fb6b8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор категории дела'),
    sa.Column('name', sa.String(length=1024), nullable=False, comment='наименование категории дела'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('judge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор судьи'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='ФИО судьи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор пользователя'),
    sa.Column('tg_id', sa.Integer(), nullable=True, comment='индентификтор пользователя в telegram'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='имя пользователя'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='фамилия пользователя'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='логин пользователя в telegram'),
    sa.Column('chat_id', sa.Integer(), nullable=True, comment='идентификтор чата с пользователем'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор карточки дела'),
    sa.Column('number', sa.String(length=255), nullable=True, comment='номер дела'),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False, comment='уникальный идентификатор дела'),
    sa.Column('judge_id', sa.Integer(), nullable=True, comment='идентификатор судьи'),
    sa.Column('name_of_the_court', sa.String(length=255), nullable=True, comment='наименование суда'),
    sa.Column('date_of_receipt', sa.String(length=255), nullable=True, comment='дата размещения'),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_identifier')
    )
    op.create_index(op.f('ix_case_judge_id'), 'case', ['judge_id'], unique=False)
    op.create_table('case_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='суррогатный ключ'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='категория дела'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='идентификтор карточки дела'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'case_id', name='uq_casecategory_case_category'),
    sa.UniqueConstraint('id')
    )
    op.create_table('case_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор события'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='наименование события'),
    sa.Column('date', sa.Date(), nullable=True, comment='дата события'),
    sa.Column('time', sa.Time(), nullable=True, comment='время события'),
    sa.Column('result', sa.String(length=255), nullable=True, comment='результат события'),
    sa.Column('the_basic_for_the_selected_result', sa.String(length=255), nullable=True, comment='Основание для выбранного результата события'),
    sa.Column('date_of_placement', sa.Date(), nullable=True, comment='дата размещения события'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='идентификтор карточки дела'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор подписки'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='идентификтор пользователя'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='идентификтор карточки дела'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_subscription_user_case')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификтор уведомления'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='идентификтор пользователя'),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='идентификтор события'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='дата отправки уведомления пользователю'),
    sa.ForeignKeyConstraint(['event_id'], ['case_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('subscription')
    op.drop_table('case_event')
    op.drop_table('case_category')
    op.drop_index(op.f('ix_case_judge_id'), table_name='case')
    op.drop_table('case')
    op.drop_table('user')
    op.drop_table('judge')
    op.drop_table('category')
    # ### end Alembic commands ###
